### ISSUE TITLE
encrypting using hive 

### ISSUE THREAD

**Issue by crypt0miester** [marc2332/solana-mobile-wallet#4]
love your work. keep it up.

perhaps this would help with the encryption of the keypair/mnemonic seed.

https://github.com/hivedb/hive/issues/556#issuecomment-770458818

maybe ask the user to create password first time the launch the app.

**Comment by crypt0miester** [comment]
sorry, just saw that you actually encrypt it. closing the issue. 

again, keep it up sir.

**Comment by marc2332** [comment]
Heheh,  I actually implemented it yesterday, previously I was only encrypting the seed phrase via a key injected in compile-time. Now it encrypts all the wallets' data via the password decided by the user 😄 

Thanks!
